const championsList = [
  {
    name: 'Aatrox',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Aatrox.png',
    id: 1,
    role: 'Top',
    open: true,
  },
  {
    name: 'Ahri',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Ahri.png',
    id: 2,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Akali',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Akali.png',
    id: 3,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Akshan',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Akshan.png',
    id: 4,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Alistar',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Alistar.png',
    id: 5,
    role: 'Support',
    open: true,
  },
  {
    name: 'Amumu',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Amumu.png',
    id: 6,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Anivia',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Anivia.png',
    id: 7,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Annie',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Annie.png',
    id: 8,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Aphelios',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Aphelios.png',
    id: 9,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Ashe',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Ashe.png',
    id: 10,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Aurelion Sol',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/AurelionSol.png',
    id: 11,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Azir',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Azir.png',
    id: 12,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Bard',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Bard.png',
    id: 13,
    role: 'Support',
    open: true,
  },
  {
    name: "Bel'veth",
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Belveth.png',
    id: 14,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Blitzcrank',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Blitzcrank.png',
    id: 15,
    role: 'Support',
    open: true,
  },
  {
    name: 'Brand',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Brand.png',
    id: 16,
    role: 'Support',
    open: true,
  },
  {
    name: 'Braum',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Braum.png',
    id: 17,
    role: 'Support',
    open: true,
  },
  {
    name: 'Caitlyn',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Caitlyn.png',
    id: 18,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Camille',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Camille.png',
    id: 19,
    role: 'Top',
    open: true,
  },
  {
    name: 'Cassiopeia',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Cassiopeia.png',
    id: 20,
    role: 'Mid',
    open: true,
  },
  {
    name: "Cho'Gath",
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Chogath.png',
    id: 21,
    role: 'Top',
    open: true,
  },
  {
    name: 'Corki',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Corki.png',
    id: 22,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Darius',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Darius.png',
    id: 23,
    role: 'Top',
    open: true,
  },
  {
    name: 'Diana',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Diana.png',
    id: 24,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Dr. Mundo',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/DrMundo.png',
    id: 25,
    role: 'Top',
    open: true,
  },
  {
    name: 'Draven',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Draven.png',
    id: 26,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Ekko',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Ekko.png',
    id: 27,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Elise',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Elise.png',
    id: 28,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Evelynn',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Evelynn.png',
    id: 29,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Ezreal',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Ezreal.png',
    id: 30,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Fiddlesticks',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Fiddlesticks.png',
    id: 31,
    role: 'Support',
    open: true,
  },
  {
    name: 'Fiora',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Fiora.png',
    id: 32,
    role: 'Top',
    open: true,
  },
  {
    name: 'Fizz',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Fizz.png',
    id: 33,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Galio',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Galio.png',
    id: 34,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Gangplank',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Gangplank.png',
    id: 35,
    role: 'Top',
    open: true,
  },
  {
    name: 'Garen',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Garen.png',
    id: 36,
    role: 'Top',
    open: true,
  },
  {
    name: 'Gnar',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Gnar.png',
    id: 37,
    role: 'Top',
    open: true,
  },
  {
    name: 'Gragas',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Gragas.png',
    id: 38,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Graves',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Graves.png',
    id: 39,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Gwen',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Gwen.png',
    id: 40,
    role: 'Top',
    open: true,
  },
  {
    name: 'Hecarim',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Hecarim.png',
    id: 41,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Heimerdinger',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Heimerdinger.png',
    id: 42,
    role: 'Mid',
    open: true,
  },
  {
    name: 'Illaoi',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Illaoi.png',
    id: 43,
    role: 'Top',
    open: true,
  },
  {
    name: 'Irelia',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Irelia.png',
    id: 44,
    role: 'Top',
    open: true,
  },
  {
    name: 'Ivern',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Ivern.png',
    id: 45,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Janna',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Janna.png',
    id: 46,
    role: 'Support',
    open: true,
  },
  {
    name: 'Jarvan IV',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/JarvanIV.png',
    id: 47,
    role: 'Jungle',
    open: true,
  },
  {
    name: 'Jax',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Jax.png',
    id: 48,
    role: 'Top',
    open: true,
  },
  {
    name: 'Jayce',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Jayce.png',
    id: 49,
    role: 'Top',
    open: true,
  },
  {
    name: 'Jhin',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Jhin.png',
    id: 50,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Jinx',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Jinx.png',
    id: 51,
    role: 'ADC',
    open: true,
  },
  {
    name: "Kai'Sa",
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Kaisa.png',
    id: 52,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Kalista',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Kalista.png',
    id: 53,
    role: 'ADC',
    open: true,
  },
  {
    name: 'Karma',
    img: 'https://ddragon.leagueoflegends.com/cdn/11.16.1/img/champion/Karma.png',
    id: 54,
    role: 'Support',
    open: true,
  },
];

export default championsList;
